apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 5dfbf66f77d44e492261c591bcff4f9a23463da3
    app.openshift.io/vcs-uri: https://github.com/mhillb/e2e-app.git
  labels:
    app.kubernetes.io/instance: e2e-app
    app.kubernetes.io/name: e2e-app
  name: express-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: e2e-app
    app.kubernetes.io/name: e2e-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 5dfbf66f77d44e492261c591bcff4f9a23463da3
    app.openshift.io/vcs-uri: https://github.com/mhillb/e2e-app.git
  labels:
    app.kubernetes.io/instance: e2e-app
    app.kubernetes.io/name: e2e-app
  name: express-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-app
      app.kubernetes.io/name: e2e-app
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 5dfbf66f77d44e492261c591bcff4f9a23463da3
        app.openshift.io/vcs-uri: https://github.com/mhillb/e2e-app.git
      labels:
        app.kubernetes.io/instance: e2e-app
        app.kubernetes.io/name: e2e-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/mhillb/e2e-app:5dfbf66f77d44e492261c591bcff4f9a23463da3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 5dfbf66f77d44e492261c591bcff4f9a23463da3
    app.openshift.io/vcs-uri: https://github.com/mhillb/e2e-app.git
  labels:
    app.kubernetes.io/instance: e2e-app
    app.kubernetes.io/name: e2e-app
  name: express-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: express-sample-app
    weight: 100
  wildcardPolicy: None
