apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 3e8bfc10842a30899097a716c760d011e5dce68f
    app.openshift.io/vcs-uri: https://github.com/tbrodbeck/facts-api.git
  labels:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
  name: facts-api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 3e8bfc10842a30899097a716c760d011e5dce68f
    app.openshift.io/vcs-uri: https://github.com/tbrodbeck/facts-api.git
  labels:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
    app.openshift.io/runtime: js
  name: facts-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: tkn-e2e-assignment
      app.kubernetes.io/name: tkn-e2e-assignment
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 3e8bfc10842a30899097a716c760d011e5dce68f
        app.openshift.io/vcs-uri: https://github.com/tbrodbeck/facts-api.git
      labels:
        app.kubernetes.io/instance: tkn-e2e-assignment
        app.kubernetes.io/name: tkn-e2e-assignment
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/tillus/facts-api:3e8bfc10842a30899097a716c760d011e5dce68f
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: facts-api
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 3e8bfc10842a30899097a716c760d011e5dce68f
    app.openshift.io/vcs-uri: https://github.com/tbrodbeck/facts-api.git
  labels:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
  name: facts-api
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: facts-api
    weight: 100
  wildcardPolicy: None
