apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: 82f9370e1564c80baed4e10afe41c81c93f14227
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea7-juan-ting-express
  labels:
    app.kubernetes.io/instance: express-assignment
    app.kubernetes.io/name: express-assignment
  name: express-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: express-app
    app.kubernetes.io/instance: express-assignment
    app.kubernetes.io/name: express-assignment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: 82f9370e1564c80baed4e10afe41c81c93f14227
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea7-juan-ting-express
  labels:
    app: express-app
    app.kubernetes.io/instance: express-assignment
    app.kubernetes.io/name: express-assignment
  name: express-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
      app.kubernetes.io/instance: express-assignment
      app.kubernetes.io/name: express-assignment
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: 82f9370e1564c80baed4e10afe41c81c93f14227
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea7-juan-ting-express
      labels:
        app: express-app
        app.kubernetes.io/instance: express-assignment
        app.kubernetes.io/name: express-assignment
    spec:
      containers:
      - image: quay.io/jm_carnicero/express-assignment:82f9370e1564c80baed4e10afe41c81c93f14227
        name: nextjs
        ports:
        - containerPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: 82f9370e1564c80baed4e10afe41c81c93f14227
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/emea7-juan-ting-express
  labels:
    app.kubernetes.io/instance: express-assignment
    app.kubernetes.io/name: express-assignment
  name: express-app
spec:
  to:
    kind: Service
    name: express-app
