apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: ae308bc8bf6a92f157fd2a26342a2dcd54a2daac
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/till-e2e-assignment-app.git
  labels:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
  name: express-sample-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: ae308bc8bf6a92f157fd2a26342a2dcd54a2daac
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/till-e2e-assignment-app.git
  labels:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
    app.openshift.io/runtime: js
  name: express-sample-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: tkn-e2e-assignment
      app.kubernetes.io/name: tkn-e2e-assignment
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ae308bc8bf6a92f157fd2a26342a2dcd54a2daac
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/till-e2e-assignment-app.git
      labels:
        app.kubernetes.io/instance: tkn-e2e-assignment
        app.kubernetes.io/name: tkn-e2e-assignment
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/tillus/cnb-tkn-e2e-assignment:ae308bc8bf6a92f157fd2a26342a2dcd54a2daac
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: express-sample-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-ref: ae308bc8bf6a92f157fd2a26342a2dcd54a2daac
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/till-e2e-assignment-app.git
  labels:
    app.kubernetes.io/instance: tkn-e2e-assignment
    app.kubernetes.io/name: tkn-e2e-assignment
  name: express-sample-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: express-sample-app
    weight: 100
  wildcardPolicy: None
